
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "23"
        
    - name: Frontend compilation
      run: | 
        cd client
        find . -name "*.js" -exec node --check {} +

    - name: Backend compilation
      run: | 
        cd server
        find . -name "*.js" -exec node --check {} +
        
  trivy_fs_scan:
    runs-on: ubuntu-24.04
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
